# Generated by Django 5.0 on 2023-12-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_category_alter_actor_is_published_actor_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='actors.tag'),
        ),
    ]
