# Generated by Django 5.0 on 2023-12-28 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0005_producer_actor_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actors', to='actors.category'),
        ),
    ]
