# Generated by Django 5.0 on 2024-01-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0006_alter_actor_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, default='static/images/default.jpg', null=True, upload_to='actors_photos/%Y/%m/%d/'),
        ),
    ]
