# Generated by Django 5.0 on 2024-01-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0007_alter_category_options_alter_tag_options_actor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='actors_photos/'),
        ),
    ]
